apiVersion: v1
kind: Service
metadata:
  name: toyeglobal-app
  namespace: prod
spec:
  selector:
    app: toyeglobal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
