apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-eyot
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: damsaji168@gmail.com
    privateKeySecretRef:
      name: letsencrypt-eyot
    solvers:
      - http01:
           ingress:
              class: nginx