apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-loki-0 
  namespace: prod 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
