apiVersion: apps/v1
kind: Deployment
metadata:
  name: inf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Equal
          key: owner
          value: red
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
